### ISSUE TITLE
How to deal with the multiprocessing in win32?

### ISSUE THREAD

**Issue by qzc438** [KRR-Oxford/BERTMap#16]
Traceback (most recent call last):
  File "run_bertmap.py", line 404, in <module>
    prepare_data(config=config_json)
  File "run_bertmap.py", line 90, in prepare_data
    data_params["cut"],
  File "D:\PycharmProjects\BERTMap\bertmap\onto\onto_box.py", line 47, in __init__
    self.onto = get_ontology(f"file://{onto_file}").load()
  File "D:\Python\Python37\lib\site-packages\owlready2\namespace.py", line 972, in load
    try:     new_base_iri = self.graph.parse(fileobj, default_base = self._orig_base_iri, **args)
  File "D:\Python\Python37\lib\site-packages\owlready2\driver.py", line 256, in parse
    multiprocessing.Process(target = do_parse).start()
  File "D:\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "D:\Python\Python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "D:\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "D:\Python\Python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'BaseSubGraph.parse.<locals>.do_parse'

**Comment by Lawhy** [comment]
Hi @qzc438, the BERTMap model is now maintained at [DeepOnto](https://github.com/KRR-Oxford/DeepOnto), where `multi_processing` is no long used. The code in DeepOnto is also easier for debugging.

I am not quite familiar with this package to be honest.
